"""add username to users

Revision ID: 17f744e5abed
Revises: fe1032780c40
Create Date: 2026-05-27 09:45:09.411147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17f744e5abed'
down_revision = 'fe1032780c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_reflections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_reflections_owner_id'))

    op.drop_table('progress_reflections')
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_logs_owner_id'))

    op.drop_table('work_logs')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_owner_id'))

    op.drop_table('notes')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_owner_id'))

    op.drop_table('topics')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_owner_id'))
        batch_op.drop_index(batch_op.f('uq_category_owner_name'))

    op.drop_table('categories')
    with op.batch_alter_table('roadmap_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_items_owner_id'))

    op.drop_table('roadmap_items')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_events_owner_id'))

    op.drop_table('activity_events')
    with op.batch_alter_table('lab_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_references_owner_id'))

    op.drop_table('lab_references')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('display_name')
        batch_op.drop_column('mfa_secret')
        batch_op.drop_column('role')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('mfa_secret', mysql.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('display_name', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('mfa_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('is_admin')
        batch_op.drop_column('username')

    op.create_table('lab_references',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('vendor', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=False),
    sa.Column('topic_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('lab_references_ibfk_2')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('lab_references_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('lab_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_references_owner_id'), ['owner_id'], unique=False)

    op.create_table('activity_events',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('intensity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('occurred_on', sa.DATE(), nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('activity_events_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_owner_id'), ['owner_id'], unique=False)

    op.create_table('roadmap_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('milestone', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('topic_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('roadmap_items_ibfk_2')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('roadmap_items_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('roadmap_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_items_owner_id'), ['owner_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('categories_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_category_owner_name'), ['owner_id', 'name'], unique=True)
        batch_op.create_index(batch_op.f('ix_categories_owner_id'), ['owner_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('priority', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('topics_ibfk_1')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('topics_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_owner_id'), ['owner_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=False),
    sa.Column('topic_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('notes_ibfk_2')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('notes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_owner_id'), ['owner_id'], unique=False)

    op.create_table('work_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('log_type', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('evidence_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('risk_rating', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('log_date', sa.DATE(), nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('work_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_logs_owner_id'), ['owner_id'], unique=False)

    op.create_table('progress_reflections',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('insight', mysql.TEXT(), nullable=False),
    sa.Column('challenge', mysql.TEXT(), nullable=False),
    sa.Column('next_step', mysql.TEXT(), nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('progress_reflections_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('progress_reflections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_reflections_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###
